# version: '3.8'
# services:
#   jenkins:
#     image: custom-jenkins
#     privileged: true
#     user: root
#     ports:
#       - 8080:8080
#       - 50000:50000
#     volumes:
#       - jenkins-data:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - jenkins-network
#   dind:
#     image: docker:dind
#     privileged: true
#     environment:
#       - DOCKER_TLS_CERTDIR=/certs
#     volumes:
#       - jenkins-data:/certs
#     networks:
#       - jenkins-network

# volumes:
#   jenkins-data:

# networks:
#   jenkins-network:
#     driver: bridge

version: '3.8'
services:
  jenkins:
    image: custom-jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network

volumes:
  jenkins-data:

networks:
  jenkins-network:
    driver: bridge