name: Next.js E-commerce CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Build Next.js app
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t nextjs-ecommerce:latest .

      - name: Save Docker image
        run: docker save -o nextjs-ecommerce.tar nextjs-ecommerce:latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-ecommerce-image
          path: nextjs-ecommerce.tar